import streamlit as st
import zipfile
import lxml.etree as ET
import pypdf

class SchemaComparator:
    def __init__(self, doc_path, pdf_path):
        self.doc_path = doc_path
        self.pdf_path = pdf_path
        self.docx_schema = self._extract_docx_schema()
        self.extracted_lineage = self._simulate_extraction_lineage()

    def _extract_docx_schema(self):
        """Extracts native XML relationship tree."""
        schema = {}
        with zipfile.ZipFile(self.doc_path) as z:
            with z.open('word/_rels/document.xml.rels') as f:
                root = ET.parse(f).getroot()
                ns = {'rels': 'http://schemas.openxmlformats.org/package/2006/relationships'}
                for rel in root.findall('.//rels:Relationship', ns):
                    schema[rel.get('Id')] = rel.get('Target')
        return schema

    def _simulate_extraction_lineage(self):
        """Captures the linear sequence inferred by the PDF engine."""
        reader = pypdf.PdfReader(self.pdf_path)
        lineage = []
        # Extraction engines infer lineage based on spatial sequence, not XML tags
        for i, page in enumerate(reader.pages):
            text = page.extract_text()
            # Simple simulation: capturing the first 50 chars of each page
            lineage.append({"Step": i + 1, "Inferred_Node": text[:50].strip()})
        return lineage

def main():
    st.title("Comparative Schema & Lineage Analyzer")
    
    col1, col2 = st.columns(2)
    with col1:
        docx_file = st.file_uploader("Source .docx", type=["docx"])
    with col2:
        pdf_file = st.file_uploader("Target Archive .pdf", type=["pdf"])

    if docx_file and pdf_file:
        comp = SchemaComparator(docx_file, pdf_file)
        
        st.subheader("Analysis: Native Structure vs. Extraction Lineage")
        
        # Display the 'False Lineage' revealing the engine's processing order
        st.write("### Extraction Engine 'Pseudolineage'")
        st.write("This sequence is generated by the extraction engine's spatial heuristics, "
                 "not the native document tree structure.")
        st.table(comp.extracted_lineage)
        
        st.write("### Structural Inventory Comparison")
        col_a, col_b = st.columns(2)
        with col_a:
            st.write("**Native XML Tree (Source)**")
            st.table([{"ID": k, "Target": v} for k, v in comp.docx_schema.items()])
        with col_b:
            st.write("**Extracted Lineage (Target)**")
            st.info("The extraction engine has reconstituted the content into the linear "
                    "sequence shown above, creating a false lineage.")

if __name__ == "__main__":
    main()
